sudo: required

language: sh

services:
  - docker

before_install:
  - shopt -s expand_aliases  # allow alias
  - shopt -s globstar  # allow use of **
  - export DOCKER_BASE_IMAGE=andrijdavid/alpine-mpich
  - export DOCKER_ONBUILD_IMAGE=andrijdavid/alpine-mpich

script:
  - sh check_scripts.sh
  - docker build --build-arg MPICH_VERSION="3.2" -t $DOCKER_BASE_IMAGE:3.2 base/
  - docker build --build-arg MPICH_VERSION="3.3" -t $DOCKER_BASE_IMAGE:3.3 base/
  - docker build --build-arg MPICH_VERSION="3.4a2" MPICH_CONFIGURE_OPTIONS="" -t $DOCKER_BASE_IMAGE:3.4a2 base/
  - docker build --build-arg MPICH_VERSION="3.3" -t $DOCKER_BASE_IMAGE:latest base/
  - docker build --build-arg TAG="latest" -t $DOCKER_ONBUILD_IMAGE:onbuild onbuild/
  - docker build --build-arg TAG="3.2" -t $DOCKER_ONBUILD_IMAGE:onbuild-3.2 onbuild/
  - docker build --build-arg TAG="3.3" -t $DOCKER_ONBUILD_IMAGE:onbuild-3.3 onbuild/

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_BASE_IMAGE:3.2
  - docker push $DOCKER_BASE_IMAGE:3.3
  - docker push $DOCKER_BASE_IMAGE:latest
  - docker push $DOCKER_ONBUILD_IMAGE:onbuild-3.2
  - docker push $DOCKER_ONBUILD_IMAGE:onbuild-3.3
  - docker push $DOCKER_ONBUILD_IMAGE:onbuild
